### PR TITLE
add tutorial notebook

### PR DESCRIPTION
**Pull request by cdonnay**
Add a getting_started tutorial notebook, as well as adding Minneapolis Mayor 2013 data to `data` folder so that users can have access to it.

@jamesturk @drdeford @jgibson517 @ziglaser @jennjwang

### CODE REVIEW

**Comment by cdonnay** [comment]
Needs to be merged after pull request #96 to allow for choice of columns in a csv file.

**Comment by jgibson517** [comment]
hi @cdonnay, thanks so much for the help on this, the tutorial notebook is amazing!!! i'd love to add it to the documentation site as well if that's ok with you!

my only comment is on adding the Minneapolis data to the repo. one, there's a similar file at `tests/data/mn_clean_ballots.csv` and let's try and avoid adding larger csv files to the repo so isn't to large to easily clone for future contributors (a previous version of this package suffered from that..). i'd suggest swapping the existing MN csv file with the one your using, since we'll want to test the `rank_columns` args and/or linking where you downloaded the file in the notebook so users can easily download it themselves!

**Comment by cdonnay** [comment]
@jgibson517 Adding it to the documentation site would be great. I will remove the csv file I added and just point people to the `mn_clean_ballots` file instead. 

In that file, do you know what an overvote and what an undervote is?

**Comment by cdonnay** [comment]
@jgibson517 not sure why my second commit is failing the 3.11 tests, particularly since the test it's failing is not related to any code I edited for this pull. But I'm new to git so totally possible that it's a me error.

**Comment by jgibson517** [comment]
since the `test_interval_from_params` is based on a probability distribution, it'll occasionally fail (its not ideal and a better test is on the to-do list). if you go to details and click re-run jobs, they should pass 🤞

**Comment by cdonnay** [comment]
@jgibson517 for some reason it isn't showing me a re-run option for the job.
Screen Shot 2023-09-13 at 2 37 17 PM

**Comment by jgibson517** [comment]
hm must be a github user permission setting, I re-ran it from my end so should be all set!

**Pull request merged**
